title:              è‡ªå·±æº€ãƒ–ãƒ­ã‚°
email:              mixpax4300@gmail.com
description:        ãªã‚“ã ã“ã®è‡ªå·±æº€ãƒ–ãƒ­ã‚°ï½œæ°—ãŒå‘ã„ãŸã‚‰æ›´æ–°ï½œãƒ—ãƒ­ã‚°ãƒ©ãƒŸãƒ³ã‚°ã¨CGï½œYSFlightSumiratorğŸ”°
author:             è‡ªå·±æº€
baseurl:            "/"
url:                "https://blog.jkmn.f5.si"

github_username:    kanxta

# Add your google-analytics ID here to activate google analytics
google_analytics:   G-GF58B65V8S # out your google-analytics code

# Build settings

# Conversion
markdown            : kramdown
highlighter         : rouge
lsi                 : false
excerpt_separator   : "\n\n"
incremental         : false

paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

kramdown:
  auto_ids          : true
  entity_output     : as_char
  toc_levels        : [1, 2, 3, 4, 5, 6]
  smart_quotes      : lsquo,rsquo,ldquo,rdquo
  input             : GFM
  hard_wrap         : false
  footnote_nr       : 1
  show_warnings     : false
